Login/LoginProject/Controllers/AspnetusersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LoginProject.Areas.Identity.Data;
using LoginProject.Models;

namespace LoginProject.Controllers
{
    public class AspnetusersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AspnetusersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Aspnetusers
        //public async Task<IActionResult> Index()
        //{
        //      return _context.Aspnetusers != null ? 
        //                  View(await _context.Aspnetusers.ToListAsync()) :
        //                  Problem("Entity set 'ApplicationDbContext.Aspnetusers'  is null.");
        //}

        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
        
            var Aspnetusers = from s in _context.Aspnetusers select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                Aspnetusers = Aspnetusers.Where(s => s.FirstName.Contains(searchString)|| s.LastName.Contains(searchString) || s.Email.Contains(searchString));
            }
            return View(await Aspnetusers.AsNoTracking().ToListAsync());
        }

        // GET: Aspnetusers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Aspnetusers == null)
            {
                return NotFound();
            }

            var aspnetusers = await _context.Aspnetusers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aspnetusers == null)
            {
                return NotFound();
            }

            return View(aspnetusers);
        }

        // GET: Aspnetusers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Aspnetusers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,IsStaff,Email")] Aspnetusers aspnetusers)
        {
            if (ModelState.IsValid)
            {
                //ModelState.SetModelValue("");
                _context.Add(aspnetusers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aspnetusers);
        }

        // GET: Aspnetusers/AddStaffRole
        public IActionResult AddStaffRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddStaffRole(string email)
        {
            // Find the user by email
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Email == email);

            if (user != null)
            {
                // Update the boolean variable
                user.Staff = true; 

                // Update the user in the database
                _context.Entry(user).State = EntityState.Modified;
                await _context.SaveChangesAsync();

                // Successful update

                TempData["SuccessMessage"] = "Staff role added successfully.";
                ViewBag.Message = TempData["SuccessMessage"];
                return View(); // Redirect to a success page
            }

            // If user is not found
            TempData["ErrorMessage"] = "User not found.";
            ViewBag.Message = TempData["ErrorMessage"];
            return View(); // Redirect to an error page or home page
        }

        // GET: Aspnetusers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Aspnetusers == null)
            {
                return NotFound();
            }

            var aspnetusers = await _context.Aspnetusers.FindAsync(id);
            if (aspnetusers == null)
            {
                return NotFound();
            }
            return View(aspnetusers);
        }

        // POST: Aspnetusers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,FirstName,LastName,IsStaff,Email")] Aspnetusers aspnetusers)
        {
            if (id != aspnetusers.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aspnetusers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AspnetusersExists(aspnetusers.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aspnetusers);
        }


        public async Task<IActionResult> RemoveStaffRole(string id)
        {
            if (id == null || _context.Aspnetusers == null)
            {
                return NotFound();
            }

            var aspnetusers = await _context.Aspnetusers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aspnetusers == null)
            {
                return NotFound();
            }

            return View(aspnetusers);
        }

        [HttpPost, ActionName("RemoveStaffRole")]
        public async Task<IActionResult> RemoveStaffRoleConfirmed(string id)
        {
            // Find the user by ID
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == id);
            

            if (user != null)
            {
                // Update the staff property
                user.Staff = false; 

                // Update the user in the database
                _context.Entry(user).State = EntityState.Modified;
                await _context.SaveChangesAsync();

                // Successful update
                return RedirectToAction("Index"); // Redirect to a success page
            }

            // If user is not found
            return RedirectToAction("Index"); // Redirect to an error page or home page
        }


        // GET: Aspnetusers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Aspnetusers == null)
            {
                return NotFound();
            }

            var aspnetusers = await _context.Aspnetusers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aspnetusers == null)
            {
                return NotFound();
            }

            return View(aspnetusers);
        }

        // POST: Aspnetusers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Aspnetusers == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Aspnetusers'  is null.");
            }
            var aspnetusers = await _context.Aspnetusers.FindAsync(id);
            if (aspnetusers != null)
            {
                _context.Aspnetusers.Remove(aspnetusers);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AspnetusersExists(string id)
        {
          return (_context.Aspnetusers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Login/LoginProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

@using Microsoft.AspNetCore.Identity;

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LoginProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LoginProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @if (this.User.Identity.IsAuthenticated)
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/Logo.png" /></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>

                            @if (this.User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Aspnetusers" asp-action="Index">Users</a>
                                </li>
                            }
                        </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LoginProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>